POST http://localhost:3001/api/persons
Content-Type: application/json

{
	"name": "Adam Alda",
	"number": "11-11-111111"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
	"foo": "bar"
}
